name: Publish to JFrog Artifactory

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ secrets.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}

      - name: Build weather-app artifact (ZIP)
        run: |
          zip -r weather-app.zip . -x ".git/*" ".github/*"

      - name: Upload to Artifactory (krishna folder)
        run: |
          jf rt u weather-app.zip generic-local/krishna/weather-app/ \
            --build-name=weather-app \
            --build-number=${{ github.run_number }} \
            --properties="commit=${{ github.sha }};branch=${{ github.ref_name }};deployed-by=kiran.krishna@aptean.com"

      - name: Publish build info to Artifactory
        run: |
          jf rt build-publish weather-app ${{ github.run_number }}

      - name: Scan with Xray
        run: |
          jf rt build-scan weather-app ${{ github.run_number }}
