name: Publish to JFrog Artifactory

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: https://trialcej2k9.jfrog.io
          JF_USER: kiran.krishna@aptean.com
          JF_PASSWORD: JFrog@1234

      - name: Build weather-app artifact (ZIP)
        run: |
          zip -r weather-app.zip . -x ".git/*" ".github/*"

      - name: Upload to Artifactory (krishna folder)
        run: |
          jf rt u "weather-app.zip" "generic-local/krishna/weather-app/" --build-name=weather-app --build-number=${{ github.run_number }}

      - name: Publish build info
        run: |
          jf rt build-publish weather-app ${{ github.run_number }}
